repos: 
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: go-mod-tidy
  - repo: local
    hooks:
      - id: ui-format
        name: ui-format
        language: system
        entry: bash -c 'cd ui && npm install && npm run format'
        files: "^ui/.*"
        pass_filenames: false
      - id: ui-lint
        name: ui-lint
        language: system
        entry: bash -c 'cd ui && npm install && npm run lint'
        files: "^ui/.*"
        pass_filenames: false
