name: lint

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38
        with:
          node-version-file: .tool-versions

      # also typechecks the ui, since vite build does not
      - name: build ui
        run: make build-ui

      - name: Lint UI
        run: make lint-ui

      - name: Lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20
        with:
          version-file: .tool-versions
