name: Test

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: .tool-versions

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .tool-versions

      # also typechecks the ui, since vite build does not
      - name: build ui
        run: make build-ui

      - name: test
        run: make cover

      - uses: jandelgado/gcov2lcov-action@e4612787670fc5b5f49026b8c29c5569921de1db
        name: convert coverage to lcov
        with:
          infile: coverage.txt
          outfile: coverage.lcov

      - name: upload to coveralls
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
          fail-on-error: false
